# Generated by Django 4.0.4 on 2022-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contacts_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_email',
            field=models.EmailField(max_length=100),
        ),
    ]
