# Generated by Django 4.0.4 on 2022-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contacts_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['contact_name']},
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact_job',
            field=models.CharField(default='', max_length=100),
        ),
    ]
