# Generated by Django 4.0.4 on 2022-04-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contacts_options_contacts_contact_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_phone',
            field=models.PositiveIntegerField(max_length=20, unique=True),
        ),
    ]
