# Generated by Django 4.0.4 on 2022-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contacts_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_phone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
