# Generated by Django 4.0.4 on 2022-06-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contacts_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['id']},
        ),
    ]
